#!/usr/bin/env php
<?php

declare (strict_types=1);

use Instability\Exception\InstabilityException;
use Instability\Metric\Abstractness;
use Instability\Metric\DMS;
use Instability\Metric\Instability;

include __DIR__ . '/../../autoload.php' ?? throw new Exception('Missing autoload file');
$instabilityFile = __DIR__ . '/../../../instability.php';

/**
 * creates config
 */
if (!is_file($instabilityFile)) {
    copy(__DIR__ . '/instability.php.sample', $instabilityFile);
}

$config = include __DIR__ . '/../../../instability.php';

try {
    Instability::create();
    Abstractness::create();
    DMS::create();
    echo "\n";
    echo "Provide statistics here\n";
} catch (InstabilityException $exception) {
    foreach ($exception->output() as $output) {
        echo $output;
    }

    exit(1);
}
