#!/usr/bin/env php
<?php

declare (strict_types=1);

use Stability\Config\ConfigLoaderFactory;
use Stability\Exception\StabilityException;
use Stability\Infrastructure\Console\ConsoleOutputWriter;
use Stability\Stability;
use Symfony\Component\Console\Output\ConsoleOutput;

if (is_file($autoload = __DIR__ . '/vendor/autoload.php')) {
    require_once $autoload;
    $basePath = __DIR__;
} elseif (is_file($autoload = __DIR__ . '/../../autoload.php')) {
    require_once $autoload;
    $basePath = __DIR__ . '/../../..';
} else {
    fwrite(
        STDERR,
        'You must set up project dependencies, please run `composer install`.',
    );
    exit(1);
}

$console = new ConsoleOutput();
$args = getopt('i', ['help', 'init', 'config:', 'debug']);

if (isset($args['help'])) {
    $console->writeln([
        '<info>Usage: stability [options]</info>',
        '',
        '<info>Options:</info>',
        '<comment>  -i, --init          Create the standard stability configuration file.</comment>',
        '<comment>  --config            Path to a custom stability configuration file.</comment>',
        '<comment>  --debug             Show debug information (exposes exception stack traces).</comment>',
        '<comment>  --help              Display this help message.</comment>',
    ]);

    exit(0);
}

if (isset($args['config'])) {
    $stabilityFile = $basePath . '/' . $args['config'];
} else {
    $stabilityFile = $basePath . '/stability.php';
}

if (isset($args['i']) || isset($args['init'])) {
    if (!is_file($stabilityFile)) {
        copy(__DIR__ . '/stability.php.sample', $stabilityFile);

        $console->writeln('<info>Stability configuration file created successfully!</info>');

        exit(0);
    }

    $console->writeln('<info>Stability configuration file already exists!</info>');

    exit(0);
}

if (!is_file($stabilityFile)) {
    $console->writeln(
            '<error>Configuration file not found. Please run `stability --init (-i)` or point to a custom file using `--config`.</error>',
    );

    exit(1);
}

$configLoader = ConfigLoaderFactory::create($stabilityFile);

try {
    $console->writeln('<info>Calculating stability metrics...</info>');
    $console->writeln('');

    Stability::create($configLoader, new ConsoleOutputWriter($console))->calculate($stabilityFile);

    $console->writeln('');
    $console->writeln('<info>Stability metrics calculated successfully!</info>');
} catch (StabilityException $exception) {
    $console->writeln("<error>{$exception->getMessage()}</error>");

    if(isset($args['debug'])) {
        $console->writeln([
            '',
            '<error>Stack trace:</error>',
            '<info>' . $exception->getTraceAsString() . '</info>',
        ]);
    }

    exit(1);
}
