#!/usr/bin/env php
<?php

declare (strict_types=1);

use Instability\Config\Config;
use Instability\Exception\StabilityException;
use Instability\Infrastructure\ConsoleOutputWriter;
use Instability\Stability;
use Symfony\Component\Console\Output\ConsoleOutput;

include __DIR__ . '/../../autoload.php' ?? throw new Exception('Missing autoload file');
$stabilityFile = __DIR__ . '/../../../stability.php';

/**
 * creates config
 */
if (!is_file($stabilityFile)) {
    copy(__DIR__ . '/stability.php.sample', $stabilityFile);
}

/**
 * @param array<string, mixed> $config
 */
$config = include __DIR__ . '/../../../stability.php';

$console = new ConsoleOutput();

try {
    $console->writeln('<info>Calculating stability metrics...</info>');
    $console->writeln('');

    Stability::create(Config::from($config), ConsoleOutputWriter::create())->calculate();

    $console->writeln('');
    $console->writeln('<info>Stability metrics calculated successfully!</info>');
} catch (StabilityException $exception) {
    $console->writeln("<error>{$exception->getMessage()}</error>");

    exit(1);
}
