#!/usr/bin/env php
<?php

declare (strict_types=1);

use Stability\Config\Config;
use Stability\Exception\StabilityException;
use Stability\Infrastructure\ConsoleOutputWriter;
use Stability\Stability;
use Symfony\Component\Console\Output\ConsoleOutput;

if (is_file($autoload = __DIR__ . '/vendor/autoload.php')) {
    require_once $autoload;
    $stabilityFile = __DIR__ . '/stability.php';
} elseif (is_file($autoload = __DIR__ . '/../../autoload.php')) {
    require_once $autoload;
    $stabilityFile = __DIR__ . '/../../../stability.php';
} else {
    fwrite(
        STDERR,
        'You must set up project dependencies, please run `composer install`.',
    );
    exit(1);
}

$console = new ConsoleOutput();
$args = getopt('i', ['init', 'config']);

if (isset($args['config'])) {
    $stabilityFile = __DIR__ . '/../../..' . $args['config'];
}

if (isset($args['i']) || isset($args['init'])) {
    if (!is_file($stabilityFile)) {
        copy(__DIR__ . '/stability.php.sample', $stabilityFile);

        $console->writeln('<info>Stability configuration file created successfully!</info>');

        exit(0);
    }

    $console->writeln('<info>Stability configuration file already exists!</info>');

    exit(0);
}

if (!is_file($stabilityFile)) {
    $console->writeln('<error>Configuration file not found. Please run `stability --init (-i)`</error>');

    exit(1);
}

$config = include __DIR__ . $stabilityFile;

try {
    $console->writeln('<info>Calculating stability metrics...</info>');
    $console->writeln('');

    Stability::create(Config::from($config), ConsoleOutputWriter::create())->calculate();

    $console->writeln('');
    $console->writeln('<info>Stability metrics calculated successfully!</info>');
} catch (StabilityException $exception) {
    $console->writeln("<error>{$exception->getMessage()}</error>");

    exit(1);
}
